name: Check
on:
  pull_request:
    branches: ['*']
  push:
    branches: [main]
concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup
      - run: uv sync --locked --all-packages --all-groups
      - run: uv run just check-format
      - run: uv run just check-code
      - run: uv run just check-security
      - run: uv run just check-audit
      - run: uv run just check-test
  db-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup
      - run: uv sync --locked --all-packages --all-groups
      - run: uv run just check-db-integration
